### 01 datetime64

In [1]:
import numpy as np
np.datetime64('2024-10-30') # numpy객체를 이용해 날짜를 생성

numpy.datetime64('2024-10-30')

In [2]:
import numpy as np

# 나노초 단위
np.datetime64(1000, 'ns')

numpy.datetime64('1970-01-01T00:00:00.000001000')

In [5]:
np.datetime64(10000000000, 'ns')

numpy.datetime64('1970-01-01T00:00:10.000000000')

In [6]:
np.datetime64(10000000000, 's')

numpy.datetime64('2286-11-20T17:46:40')

In [7]:
np.datetime64(1000, 'D')

numpy.datetime64('1972-09-27')

### 02 array()

In [8]:
np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype = 'datetime64')

array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype='datetime64[D]')

In [9]:
# 달단위
np.array(['2007-07-13', '2006-01-13', '2010-08-13'], dtype = 'datetime64[M]')

array(['2007-07', '2006-01', '2010-08'], dtype='datetime64[M]')

### 03 arange()

In [12]:
# 달단위
np.arange('2005-02', '2006-03', dtype = 'datetime64[M]')

array(['2005-02', '2005-03', '2005-04', '2005-05', '2005-06', '2005-07',
       '2005-08', '2005-09', '2005-10', '2005-11', '2005-12', '2006-01',
       '2006-02'], dtype='datetime64[M]')

In [14]:
# 주단위
np.arange('2005-02', '2006-03', dtype = 'datetime64[W]')

array(['2005-01-27', '2005-02-03', '2005-02-10', '2005-02-17',
       '2005-02-24', '2005-03-03', '2005-03-10', '2005-03-17',
       '2005-03-24', '2005-03-31', '2005-04-07', '2005-04-14',
       '2005-04-21', '2005-04-28', '2005-05-05', '2005-05-12',
       '2005-05-19', '2005-05-26', '2005-06-02', '2005-06-09',
       '2005-06-16', '2005-06-23', '2005-06-30', '2005-07-07',
       '2005-07-14', '2005-07-21', '2005-07-28', '2005-08-04',
       '2005-08-11', '2005-08-18', '2005-08-25', '2005-09-01',
       '2005-09-08', '2005-09-15', '2005-09-22', '2005-09-29',
       '2005-10-06', '2005-10-13', '2005-10-20', '2005-10-27',
       '2005-11-03', '2005-11-10', '2005-11-17', '2005-11-24',
       '2005-12-01', '2005-12-08', '2005-12-15', '2005-12-22',
       '2005-12-29', '2006-01-05', '2006-01-12', '2006-01-19',
       '2006-01-26', '2006-02-02', '2006-02-09', '2006-02-16'],
      dtype='datetime64[W]')

In [17]:
# 일단위
np.arange('2005-02', '2006-03', dtype = 'datetime64[D]')

array(['2005-02-01', '2005-02-02', '2005-02-03', '2005-02-04',
       '2005-02-05', '2005-02-06', '2005-02-07', '2005-02-08',
       '2005-02-09', '2005-02-10', '2005-02-11', '2005-02-12',
       '2005-02-13', '2005-02-14', '2005-02-15', '2005-02-16',
       '2005-02-17', '2005-02-18', '2005-02-19', '2005-02-20',
       '2005-02-21', '2005-02-22', '2005-02-23', '2005-02-24',
       '2005-02-25', '2005-02-26', '2005-02-27', '2005-02-28',
       '2005-03-01', '2005-03-02', '2005-03-03', '2005-03-04',
       '2005-03-05', '2005-03-06', '2005-03-07', '2005-03-08',
       '2005-03-09', '2005-03-10', '2005-03-11', '2005-03-12',
       '2005-03-13', '2005-03-14', '2005-03-15', '2005-03-16',
       '2005-03-17', '2005-03-18', '2005-03-19', '2005-03-20',
       '2005-03-21', '2005-03-22', '2005-03-23', '2005-03-24',
       '2005-03-25', '2005-03-26', '2005-03-27', '2005-03-28',
       '2005-03-29', '2005-03-30', '2005-03-31', '2005-04-01',
       '2005-04-02', '2005-04-03', '2005-04-04', '2005-04-05',
       '2005-04-06', '2005-04-07', '2005-04-08', '2005-04-09',
       '2005-04-10', '2005-04-11', '2005-04-12', '2005-04-13',
       '2005-04-14', '2005-04-15', '2005-04-16', '2005-04-17',
       '2005-04-18', '2005-04-19', '2005-04-20', '2005-04-21',
       '2005-04-22', '2005-04-23', '2005-04-24', '2005-04-25',
       '2005-04-26', '2005-04-27', '2005-04-28', '2005-04-29',
       '2005-04-30', '2005-05-01', '2005-05-02', '2005-05-03',
       '2005-05-04', '2005-05-05', '2005-05-06', '2005-05-07',
       '2005-05-08', '2005-05-09', '2005-05-10', '2005-05-11',
       '2005-05-12', '2005-05-13', '2005-05-14', '2005-05-15',
       '2005-05-16', '2005-05-17', '2005-05-18', '2005-05-19',
       '2005-05-20', '2005-05-21', '2005-05-22', '2005-05-23',
       '2005-05-24', '2005-05-25', '2005-05-26', '2005-05-27',
       '2005-05-28', '2005-05-29', '2005-05-30', '2005-05-31',
       '2005-06-01', '2005-06-02', '2005-06-03', '2005-06-04',
       '2005-06-05', '2005-06-06', '2005-06-07', '2005-06-08',
       '2005-06-09', '2005-06-10', '2005-06-11', '2005-06-12',
       '2005-06-13', '2005-06-14', '2005-06-15', '2005-06-16',
       '2005-06-17', '2005-06-18', '2005-06-19', '2005-06-20',
       '2005-06-21', '2005-06-22', '2005-06-23', '2005-06-24',
       '2005-06-25', '2005-06-26', '2005-06-27', '2005-06-28',
       '2005-06-29', '2005-06-30', '2005-07-01', '2005-07-02',
       '2005-07-03', '2005-07-04', '2005-07-05', '2005-07-06',
       '2005-07-07', '2005-07-08', '2005-07-09', '2005-07-10',
       '2005-07-11', '2005-07-12', '2005-07-13', '2005-07-14',
       '2005-07-15', '2005-07-16', '2005-07-17', '2005-07-18',
       '2005-07-19', '2005-07-20', '2005-07-21', '2005-07-22',
       '2005-07-23', '2005-07-24', '2005-07-25', '2005-07-26',
       '2005-07-27', '2005-07-28', '2005-07-29', '2005-07-30',
       '2005-07-31', '2005-08-01', '2005-08-02', '2005-08-03',
       '2005-08-04', '2005-08-05', '2005-08-06', '2005-08-07',
       '2005-08-08', '2005-08-09', '2005-08-10', '2005-08-11',
       '2005-08-12', '2005-08-13', '2005-08-14', '2005-08-15',
       '2005-08-16', '2005-08-17', '2005-08-18', '2005-08-19',
       '2005-08-20', '2005-08-21', '2005-08-22', '2005-08-23',
       '2005-08-24', '2005-08-25', '2005-08-26', '2005-08-27',
       '2005-08-28', '2005-08-29', '2005-08-30', '2005-08-31',
       '2005-09-01', '2005-09-02', '2005-09-03', '2005-09-04',
       '2005-09-05', '2005-09-06', '2005-09-07', '2005-09-08',
       '2005-09-09', '2005-09-10', '2005-09-11', '2005-09-12',
       '2005-09-13', '2005-09-14', '2005-09-15', '2005-09-16',
       '2005-09-17', '2005-09-18', '2005-09-19', '2005-09-20',
       '2005-09-21', '2005-09-22', '2005-09-23', '2005-09-24',
       '2005-09-25', '2005-09-26', '2005-09-27', '2005-09-28',
       '2005-09-29', '2005-09-30', '2005-10-01', '2005-10-02',
       '2005-10-03', '2005-10-04', '2005-10-05', '2005-10-06',
       '2005-10-07', '2005-10-08', '2005-10-09', '2005-10-10',
       '2005-10-11', '2005-10-12', '2005-10-13', '2005-10-14',
       '2005-10-15', '2005-10-16', '2005-10-17', '2005-10-18',
       '2005-10-19', '2005-10-20', '2005-10-21', '2005-10-22',
       '2005-10-23', '2005-10-24', '2005-10-25', '2005-10-26',
       '2005-10-27', '2005-10-28', '2005-10-29', '2005-10-30',
       '2005-10-31', '2005-11-01', '2005-11-02', '2005-11-03',
       '2005-11-04', '2005-11-05', '2005-11-06', '2005-11-07',
       '2005-11-08', '2005-11-09', '2005-11-10', '2005-11-11',
       '2005-11-12', '2005-11-13', '2005-11-14', '2005-11-15',
       '2005-11-16', '2005-11-17', '2005-11-18', '2005-11-19',
       '2005-11-20', '2005-11-21', '2005-11-22', '2005-11-23',
       '2005-11-24', '2005-11-25', '2005-11-26', '2005-11-27',
       '2005-11-28', '2005-11-29', '2005-11-30', '2005-12-01',
       '2005-12-02', '2005-12-03', '2005-12-04', '2005-12-05',
       '2005-12-06', '2005-12-07', '2005-12-08', '2005-12-09',
       '2005-12-10', '2005-12-11', '2005-12-12', '2005-12-13',
       '2005-12-14', '2005-12-15', '2005-12-16', '2005-12-17',
       '2005-12-18', '2005-12-19', '2005-12-20', '2005-12-21',
       '2005-12-22', '2005-12-23', '2005-12-24', '2005-12-25',
       '2005-12-26', '2005-12-27', '2005-12-28', '2005-12-29',
       '2005-12-30', '2005-12-31', '2006-01-01', '2006-01-02',
       '2006-01-03', '2006-01-04', '2006-01-05', '2006-01-06',
       '2006-01-07', '2006-01-08', '2006-01-09', '2006-01-10',
       '2006-01-11', '2006-01-12', '2006-01-13', '2006-01-14',
       '2006-01-15', '2006-01-16', '2006-01-17', '2006-01-18',
       '2006-01-19', '2006-01-20', '2006-01-21', '2006-01-22',
       '2006-01-23', '2006-01-24', '2006-01-25', '2006-01-26',
       '2006-01-27', '2006-01-28', '2006-01-29', '2006-01-30',
       '2006-01-31', '2006-02-01', '2006-02-02', '2006-02-03',
       '2006-02-04', '2006-02-05', '2006-02-06', '2006-02-07',
       '2006-02-08', '2006-02-09', '2006-02-10', '2006-02-11',
       '2006-02-12', '2006-02-13', '2006-02-14', '2006-02-15',
       '2006-02-16', '2006-02-17', '2006-02-18', '2006-02-19',
       '2006-02-20', '2006-02-21', '2006-02-22', '2006-02-23',
       '2006-02-24', '2006-02-25', '2006-02-26', '2006-02-27',
       '2006-02-28'], dtype='datetime64[D]')

In [18]:
# 시간단위
np.arange('2005-02', '2006-03', dtype = 'datetime64[h]')

array(['2005-02-01T00', '2005-02-01T01', '2005-02-01T02', ...,
       '2006-02-28T21', '2006-02-28T22', '2006-02-28T23'],
      dtype='datetime64[h]')

### 04 datetime64를 이용한 날짜 차이 구하기

In [19]:
# 2009년 1월 1일 - 2008년 1월
np.datetime64('2009-01-01') - np.datetime64('2008-01')

numpy.timedelta64(366,'D')

In [21]:
# 2009년 1월 1일 - 2008년 1월 1일
np.datetime64('2009-01-01') - np.datetime64('2008-01-01')

numpy.timedelta64(366,'D')

In [22]:
# 2009년 - 2008년 1월
np.datetime64('2009') - np.datetime64('2008-01')

numpy.timedelta64(12,'M')